import Footer from '@/components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundColor: '#f0d7ca'}}>
        <Navbar/>
        <div className='min-h-screen w-full max-w-screen-xl mx-auto  pt-32 '>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
